name: moving_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intro_screen_onboarding_flutter: ^1.0.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.18
  flutter_spinkit: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  sizer: ^2.0.15
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  connectivity_plus: ^3.0.3
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  get: ^4.6.5
  fancy_bar: ^2.0.0
  banner_carousel: ^1.2.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
